stages:
  - builds
  - run
  - tests
  - cleanup

variables:
  CACHE_DIR: "/lustre/f2/scratch/oar.gfdl.ogrp-account/runner/cache/"


# Merges SIS2 with dev/gfdl. Changes directory to test directory, if it exists.
# - set cache location
# - get MOM6-examples/tools/MRS scripts by cloning Gaea-stats and then MOM6-examples
# - set working directory to MOM6-examples
# - pull down latest of dev/gfdl (MOM6-examples might be ahead of Gaea-stats)
before_script:
  - echo Cache directory set to $CACHE_DIR
  - echo -e "\e[0Ksection_start:`date +%s`:before[collapsed=true]\r\e[0KPre-script"
  - git clone https://gitlab.gfdl.noaa.gov/ogrp/Gaea-stats-MOM6-examples.git tests
  - cd tests && git submodule init && git submodule update
  - cd MOM6-examples && git checkout dev/gfdl && git pull
  - echo -e "\e[0Ksection_end:`date +%s`:before\r\e[0K"

# Tests that merge with dev/gfdl works.
merge:
  stage: builds
  tags:
    - ncrc5
  script:
    - cd $CI_PROJECT_DIR
    - git pull --no-edit https://github.com/NOAA-GFDL/SIS2.git dev/gfdl

# Compiles
gnu:repro:
  stage: builds
  tags:
    - ncrc5
  script:
    - time make -f tools/MRS/Makefile SIS2_SRC=../.. pipeline-build-repro-gnu -s -j

#gnu:ice-ocean-nolibs:
#  stage: builds
#  tags:
#    - ncrc5
#  script:
#    - make -f tools/MRS/Makefile SIS2_SRC=../.. pipeline-build-gnu-iceocean-nolibs

intel:repro:
  stage: builds
  tags:
    - ncrc5
  script:
    - time make -f tools/MRS/Makefile SIS2_SRC=../.. pipeline-build-repro-intel -s -j

pgi:repro:
  stage: builds
  tags:
    - ncrc5
  script:
    - time make -f tools/MRS/Makefile SIS2_SRC=../.. pipeline-build-repro-pgi -s -j

gnu:debug:
  stage: builds
  tags:
    - ncrc5
  script:
    - time make -f tools/MRS/Makefile SIS2_SRC=../.. pipeline-build-debug-gnu -s -j

# Runs
run:
  stage: run
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile sis2-pipeline-run

# Tests
gnu:non-symmetric:
  stage: tests
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile sis2-pipeline-test-gnu_non_symmetric

gnu:symmetric:
  stage: tests
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile sis2-pipeline-test-gnu_symmetric

gnu:memory:
  stage: tests
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile sis2-pipeline-test-gnu_memory

#gnu:static:
#  stage: tests
#  tags:
#    - ncrc5
#  script:
#    - make -f tools/MRS/Makefile sis2-pipeline-test-gnu_static

gnu:restart:
  stage: tests
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile sis2-pipeline-test-gnu_restarts

gnu:params:
  stage: tests
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile sis2-pipeline-test-params_gnu_symmetric
  allow_failure: true

intel:symmetric:
  stage: tests
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile sis2-pipeline-test-intel_symmetric

intel:non-symmetric:
  stage: tests
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile sis2-pipeline-test-intel_non_symmetric

intel:memory:
  stage: tests
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile sis2-pipeline-test-intel_memory

pgi:symmetric:
  stage: tests
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile sis2-pipeline-test-pgi_symmetric

pgi:non-symmetric:
  stage: tests
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile sis2-pipeline-test-pgi_non_symmetric

pgi:memory:
  stage: tests
  tags:
    - ncrc5
  script:
    - make -f tools/MRS/Makefile sis2-pipeline-test-pgi_memory

cleanup:
  stage: cleanup
  tags:
    - ncrc5
  before_script:
    - echo Skipping submodule update
  script:
    - rm $CACHE_DIR/*$CI_PIPELINE_ID.tgz
